### ISSUE TITLE
Problem with configuration step - Configuration, Steps, 4.II

### ISSUE THREAD

**Issue by jaceks2106** [OS2iot/OS2IoT-docs#12]
Hi, 

I have problems with going through the one step in the KOMBIT configuration ([Steps, 4.II](https://github.com/OS2iot/OS2IoT-docs/blob/master/source/kombit-adgangsstyring/kombit-adgangsstyring.rst#configuration)). I can't find anywhere option with Jobfunktionrolle.

Best regards
Jacek

**Comment by Joiversen** [comment]
Hi @jaceks2106,

According to this "how to use Kombit Adgangstyring" video guide in danish: https://digitaliseringskataloget.dk/kom-godt-i-gang-vejledninger - it sounds like that step has to be perform by the related municipality itself. 

Here's a screendump of where to find "Jobfunktionsrolle" if one has the permission to view it: 
<img width="905" alt="Skærmbillede 2021-06-28 kl  12 45 04" src="https://user-images.githubusercontent.com/58931435/123624395-cae3ca80-d80e-11eb-9575-3043281b5abc.png">

Best 
Jonas

**Comment by jaceks2106** [comment]
@Joiversen Ok, but what if I do not have such tab, what I can do? Do you have any test configuration? I want to do the whole testing on my local machine. Is it possible without this whole KOMBIT configuration?

Regards,
Jacek

**Comment by Joiversen** [comment]
Yes it is. The KOMBIT configuration is only relevant for danish municipality. The system can just fine function without it as it has its own built in permission control.

**Comment by jaceks2106** [comment]
Thank you for your all help. I forgot that there are credentials for local testing under this link https://os2iot.readthedocs.io/en/latest/users-notes/users-notes.html 

Best regards
Jacek
