### ISSUE TITLE
Maintainer status on readthedocs

### ISSUE THREAD

**Issue by VirtualSatai** [OS2iot/OS2IoT-docs#16]
Hello current maintainers of OS2IoT!
I'd like to hand over the control of the readthedocs for OS2IoT. Can you please log in to it using your Github user or make one and post the name here:
![image](https://user-images.githubusercontent.com/1919650/140487071-df7474fc-4dc6-462e-acc2-44119a98e211.png)

**Comment by ramogens** [comment]
Hi @VirtualSatai 
That sounds like an excellent idea. Please hand it over to Ramogens (Mogens Kjeldsen)
Thanks!

**Comment by VirtualSatai** [comment]
Hi @ramogens.
Did you create a user on read the docs, or at least login with your Github account?
![image](https://user-images.githubusercontent.com/1919650/140662230-1df73f46-e09e-4f08-9086-a7f4aa906b73.png)

**Comment by ramogens** [comment]
Hi @VirtualSatai 
I created a user using my github login: https://readthedocs.org/profiles/ramogens/ 
Looked through my settings and can't find anything that should make me non-searchable...

**Comment by ramogens** [comment]
Oh, strange but I guess you're right. I've removed you as a maintainer and also removed you from notifications.
Thanks!
